---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: macosx-10.10
    driver:
      box: roboticcheese/macosx-10.10
      ssh:
        insert_key: false
      gui: true
  - name: windows-2012
    driver:
      box: roboticcheese/windows-2012

suites:
  - name: default
    run_list:
      - recipe[divvy]
    attributes:
      mac_app_store:
        username: <%= ENV['APPLE_ID_USERNAME'] %>
        password: <%= ENV['APPLE_ID_PASSWORD'] %>
  - name: mac_direct_download
    run_list:
      - recipe[divvy_test::mac_direct_download]
    attributes:
    excludes:
      - windows-2012
